### ISSUE TITLE
bulk annotation file missed for this dataset

### ISSUE THREAD

**Issue by lidaof** [IDR/idr0043-uhlen-humanproteinatlas#30]
Hi there,

Seems the bulk annotation file missed for this dataset in the IDR website.
thanks

**Comment by sbesson** [comment]
Hi @lidaof,

for technical considerations related to the incremental nature of the HPA submission, there is no single bulk annotation attached to the top-level project in the IDR website. However, a bulk annotation is created and attached for each dataset and includes all the curated annotatinos with a given antibody - see the Attachments tab of https://idr.openmicroscopy.org/webclient/?show=dataset-9590 for instance.

**Comment by lidaof** [comment]
i see, thank you @sbesson !
